/**
 * Rewrites the generated parts of a node page in place: the AUTO blocks, their import lines and
 * the generator-owned frontmatter keys. Hand-written prose is left alone.
 */
import type { NodeDoc } from './extract.ts';
import {
	IMPORT_LINES,
	IMPORT_MARKER,
	RENAMED_SECTIONS,
	SECTION_ORDER,
	type RenderContext,
	type SectionName,
	frontmatterFor,
	renderBlock,
	renderCallout,
	renderDeps,
	renderFallback,
	renderOutputs,
	renderRecipes,
	renderSettings,
	renderTryIt
} from './render.ts';

/** Scaffold lines from the first docs pass that must never come back. */
export const FILLER = [
	/^\s*\|.*Source-backed field from the node schema\..*\|\s*$/,
	/^\s*-?\s*This node has source tests;.*$/,
	/^\s*-?\s*No dedicated source test.*$/,
	/^\s*-?\s*No explicit credential or node dependency is declared.*$/,
	/^Returns the extracted page data or the result of the page interaction\.$/,
	/^Returns a chat model dependency that can be connected to AI agent nodes\.$/,
	/^Returns transformed data for downstream nodes\.$/,
	/^Returns node-specific output described by the implementation.*$/,
	/^Returns the service response or a success object from the selected operation\.$/,
	/^Returns an embeddings dependency for vector stores and retrieval workflows\.$/,
	/^Starts the workflow and passes trigger context to downstream nodes when context is available\.$/,
	/^Returns the original input, filtered input, branched output, merged items, loop state, or an intentional error depending on the node\.$/,
	/^Passes data into or out of a lambda workflow, or exposes a lambda workflow as a reusable node\.$/,
	/^Returns a text splitter dependency used before indexing or retrieval\.$/
];

const START = (name: string) => `{/* AUTO:${name}:start */}`;
const END = (name: string) => `{/* AUTO:${name}:end */}`;

function splitFrontmatter(src: string): { fm: string[]; body: string } {
	const m = src.match(/^---\n([\s\S]*?)\n---\n?/);
	if (!m) return { fm: [], body: src };
	return { fm: m[1].split('\n'), body: src.slice(m[0].length) };
}

/** Drop top-level keys (and their indented children) from frontmatter lines. */
function dropKeys(lines: string[], keys: string[]): string[] {
	const out: string[] = [];
	let skipping = false;
	for (const line of lines) {
		const top = line.match(/^([A-Za-z][\w-]*):/);
		if (top) skipping = keys.includes(top[1]);
		else if (!/^\s/.test(line) && line.trim() !== '') skipping = false;
		if (!skipping) out.push(line);
	}
	return out;
}

/** Deprecated nodes leave the autogenerated sidebar; they are listed in the "Deprecated" group. */
function setSidebarHidden(lines: string[], hidden: boolean): string[] {
	const out = [...lines];
	let i = out.findIndex((l) => /^sidebar:\s*$/.test(l));
	if (i === -1) {
		if (!hidden) return out;
		out.push('sidebar:');
		i = out.length - 1;
	}
	let end = i + 1;
	while (end < out.length && /^\s+\S/.test(out[end])) end++;
	const children = out.slice(i + 1, end).filter((l) => !/^\s+hidden:/.test(l));
	if (hidden) children.push('  hidden: true');
	return [...out.slice(0, i + 1), ...children, ...out.slice(end)];
}

/** Remove the first Markdown table in a block of lines (the old hand-written settings table). */
function removeFirstTable(lines: string[]): string[] {
	const start = lines.findIndex((l) => /^\s*\|/.test(l));
	if (start === -1) return lines;
	let end = start;
	while (end < lines.length && /^\s*\|/.test(lines[end])) end++;
	return [...lines.slice(0, start), ...lines.slice(end)];
}

type Section = { heading: string; lines: string[] };

function parseSections(body: string): { preamble: string[]; sections: Section[] } {
	const lines = body.split('\n');
	const preamble: string[] = [];
	const sections: Section[] = [];
	let current: Section | undefined;
	let inFence = false;
	for (const line of lines) {
		if (/^\s*(```|~~~)/.test(line)) inFence = !inFence;
		const h = !inFence && line.match(/^## (.+?)\s*$/);
		if (h) {
			current = { heading: RENAMED_SECTIONS[h[1]] ?? h[1], lines: [] };
			sections.push(current);
		} else if (current) current.lines.push(line);
		else preamble.push(line);
	}
	return { preamble, sections };
}

function trimBlank(lines: string[]): string[] {
	let a = 0;
	let b = lines.length;
	while (a < b && lines[a].trim() === '') a++;
	while (b > a && lines[b - 1].trim() === '') b--;
	return lines.slice(a, b);
}

/** Replace (or remove, when body is empty) an AUTO block; insert it when missing. */
function setBlock(lines: string[], name: string, body: string, opts: { replaceTable?: boolean; atEnd?: boolean } = {}): string[] {
	const s = lines.findIndex((l) => l.trim() === START(name));
	const e = lines.findIndex((l) => l.trim() === END(name));
	const block = body ? renderBlock(name, body).split('\n') : [];
	if (s !== -1 && e > s) return [...lines.slice(0, s), ...block, ...lines.slice(e + 1)];
	if (!body) return lines;
	let rest = lines;
	if (opts.replaceTable) rest = removeFirstTable(rest);
	if (opts.atEnd) return [...trimBlank(rest), '', ...block];
	return ['', ...block, '', ...trimBlank(rest)];
}

function insertSection(sections: Section[], heading: SectionName): Section {
	const sec: Section = { heading, lines: [] };
	const idx = SECTION_ORDER.indexOf(heading);
	const after = sections.findIndex((s) => {
		const i = SECTION_ORDER.indexOf(s.heading as SectionName);
		return i !== -1 && i > idx;
	});
	if (after === -1) sections.push(sec);
	else sections.splice(after, 0, sec);
	return sec;
}

export function updatePage(src: string, n: NodeDoc, ctx: RenderContext): string {
	const { fm, body } = splitFrontmatter(src);
	let fmLines = [...dropKeys(fm, ['kind', 'section', 'worksIn', 'node']), ...frontmatterFor(n).split('\n')];
	fmLines = setSidebarHidden(fmLines, !!n.deprecated);

	let { preamble, sections } = parseSections(body);
	for (const s of sections) s.lines = s.lines.filter((l) => !FILLER.some((re) => re.test(l)));

	// Imports first, then the hand-written intro, then the credential callout.
	preamble = preamble.filter((l) => !l.trimEnd().endsWith(IMPORT_MARKER));
	preamble = setBlock(trimBlank(preamble), 'callout', renderCallout(n, ctx), { atEnd: true });
	preamble = [...IMPORT_LINES, '', ...trimBlank(preamble)];

	const blocks: { name: string; heading: SectionName; body: string; optional?: boolean; replaceTable?: boolean }[] = [
		{ name: 'tryit', heading: 'Try it', body: renderTryIt(n, ctx), optional: true },
		{
			name: 'settings',
			heading: 'Inputs and settings',
			body: [renderSettings(n), renderFallback(n)].filter(Boolean).join('\n\n'),
			replaceTable: true
		},
		{ name: 'outputs', heading: 'Outputs', body: renderOutputs(n) },
		{ name: 'deps', heading: 'Dependencies and credentials', body: renderDeps(n, ctx) },
		{ name: 'recipes', heading: 'Recipes with this node', body: renderRecipes(n, ctx), optional: true }
	];

	for (const b of blocks) {
		let sec = sections.find((s) => s.heading === b.heading);
		if (!sec) {
			if (b.optional && !b.body) continue;
			sec = insertSection(sections, b.heading);
		}
		sec.lines = setBlock(sec.lines, b.name, b.body, { replaceTable: b.replaceTable });
		// A generator-only section with nothing left to show goes away.
		if (b.optional && !b.body && !trimBlank(sec.lines).length) sections.splice(sections.indexOf(sec), 1);
	}

	const parts: string[] = [];
	parts.push(trimBlank(preamble).join('\n'));
	for (const s of sections) {
		const lines = trimBlank(s.lines);
		parts.push(`## ${s.heading}${lines.length ? '\n\n' + lines.join('\n') : ''}`);
	}
	const out = `---\n${fmLines.join('\n')}\n---\n\n${parts.filter((p) => p !== '').join('\n\n')}\n`;
	return out.replace(/\n{3,}/g, '\n\n');
}
