// @ts-check
/**
 * Nodes topic sidebar (awflow/Agentic-Flow#1337), built from src/data/nodes.json and
 * src/data/integration-groups.json when astro.config.mjs loads:
 *   - one group per node family (autogenerated from its folder),
 *   - integrations sub-grouped by use case,
 *   - deprecated nodes in a collapsed "Deprecated" group with badges (their pages carry
 *     `sidebar.hidden`, set by the generator, so they leave the autogenerated groups).
 * It also refuses to build while placeholder text is on a node page (#1338).
 */
import { existsSync, readFileSync } from 'node:fs';
import { join } from 'node:path';
import { assertNoFiller } from './filler.mjs';
import { groupIntegrations, newestMinor } from './shared.mjs';

const ROOT = join(import.meta.dirname, '..', '..');

/** @returns {any} */
const readJson = (/** @type {string} */ rel) => {
	const p = join(ROOT, rel);
	return existsSync(p) ? JSON.parse(readFileSync(p, 'utf8')) : undefined;
};

const family = (/** @type {string} */ label, /** @type {string} */ directory) => ({
	label,
	collapsed: true,
	items: [{ autogenerate: { directory, collapsed: true } }],
});

export function nodesSidebar() {
	assertNoFiller(join(ROOT, 'src/content/docs/nodes'));

	/** @type {{ id: string; name: string; family: string; since?: string; deprecated?: boolean }[]} */
	const nodes = readJson('src/data/nodes.json') ?? [];
	const byId = new Map(nodes.map((n) => [n.id, n]));
	const latest = newestMinor(nodes);
	const isNew = (/** @type {{since?: string}} */ n) => !!latest && !!n.since?.startsWith(latest + '.');

	const link = (/** @type {string} */ id) => {
		const n = byId.get(id);
		return {
			slug: `nodes/${id}`,
			...(n ? { label: n.name } : {}),
			...(n && isNew(n) ? { badge: { text: 'New', variant: 'tip' } } : {}),
		};
	};

	const deprecated = nodes.filter((n) => n.deprecated).sort((a, b) => a.name.localeCompare(b.name));

	return [
		{ label: 'Node catalog', link: '/nodes/' },
		{ label: 'Built-in overview', link: '/nodes/builtin/' },
		family('Triggers', 'nodes/builtin/trigger'),
		family('Lambda', 'nodes/builtin/lambda'),
		family('In-page actions', 'nodes/extension'),
		family('Flow', 'nodes/builtin/flow'),
		family('Data transformation', 'nodes/builtin/datatransformation'),
		family('Core', 'nodes/builtin/core'),
		family('AI', 'nodes/builtin/ai'),
		{
			label: 'Integrations',
			collapsed: true,
			items: groupIntegrations(nodes, readJson('src/data/integration-groups.json')).map((g) => ({
				label: g.label,
				collapsed: true,
				items: g.nodes.map(link),
			})),
		},
		{ label: 'Rate limits', link: '/nodes/builtin/rate-limits/' },
		{ label: 'Unknown node', link: '/nodes/builtin/unknownode/' },
		...(deprecated.length
			? [
					{
						label: 'Deprecated',
						collapsed: true,
						items: deprecated.map((n) => ({
							slug: `nodes/${n.id}`,
							label: n.name,
							badge: { text: 'Deprecated', variant: 'caution' },
						})),
					},
				]
			: []),
	];
}
