/**
 * Recipe data for the Recipes components (awflow/Agentic-Flow#1342). src/data/recipes.json is
 * generated by `bun run recipes:build` from the recipe pages' frontmatter and their .awf files.
 */
import RECIPES from '../../data/recipes.json';

export type RecipeLevel = 'beginner' | 'intermediate' | 'advanced';
export type RecipeSetup = 'none' | 'connection' | 'on-device';

export interface RecipeNode {
	/** Node id inside the .awf. */
	id: string;
	/** Name the workflow gives the step. */
	label: string;
	registryId: string;
	/** Node type, as the node reference names it. */
	type: string;
	family: string;
	attachment: boolean;
	docLink: string | null;
}

export interface Recipe {
	slug: string;
	href: string;
	title: string;
	description: string;
	goal: string;
	level: RecipeLevel;
	minutes: number;
	setup: RecipeSetup;
	apps: string[];
	/** Registry ids of the nodes the workflow uses. */
	nodes: string[];
	awf: string;
	marketplaceId: string | null;
	graph: RecipeNode[];
	needs: { label: string; href?: string }[];
	touches: { capabilities: string[]; domains: string[]; dynamic: boolean; apps: string[]; models: string[] };
}

/** Goal chips, in the order the index shows them. A recipe's `goal` must be one of these. */
export const GOALS = [
	'Research & reading',
	'Capture to my apps',
	'Monitor pages',
	'Fill forms & click',
	'Extract data',
	'Write with AI',
	'Chat with my knowledge',
] as const;

const goalRank = (g: string) => {
	const i = (GOALS as readonly string[]).indexOf(g);
	if (i < 0) throw new Error(`Recipe goal "${g}" is not one of: ${GOALS.join(', ')}.`);
	return i;
};

/** All recipes, grouped in goal order (then by level and time). */
export const recipes = [...(RECIPES as Recipe[])].sort(
	(a, b) => goalRank(a.goal) - goalRank(b.goal) || a.minutes - b.minutes,
);

export const LEVEL_LABEL: Record<RecipeLevel, string> = {
	beginner: 'Beginner',
	intermediate: 'Intermediate',
	advanced: 'Advanced',
};

export const SETUP: Record<RecipeSetup, { label: string; variant: string }> = {
	none: { label: 'No setup', variant: 'no-setup' },
	connection: { label: 'Needs a connection', variant: 'connections' },
	'on-device': { label: 'On-device AI', variant: 'on-device' },
};

export const MARKETPLACE_URL = 'https://app.awflow.io/#/app/marketplace';

export function marketplaceHref(r: Pick<Recipe, 'marketplaceId'>): string | null {
	return r.marketplaceId ? `${MARKETPLACE_URL}/${encodeURIComponent(r.marketplaceId)}` : null;
}

/** Throws at build time when a page names a recipe that recipes.json does not have. */
export function getRecipe(slug: string): Recipe {
	const r = recipes.find((x) => x.slug === slug);
	if (!r) throw new Error(`Recipe "${slug}" is not in src/data/recipes.json. Run \`bun run recipes:build\`.`);
	return r;
}
