import { defineRouteMiddleware } from '@astrojs/starlight/route-data';
import config from 'virtual:starlight-awflow/config';
import nodesData from 'virtual:starlight-awflow/nodes';
import { findNodeEntry, normaliseNode } from './lib/nodes';
import { scopePagination } from './lib/pagination';
import type { AwflowRouteData, AwflowSection, AwflowTab } from './types';

const trimSlashes = (s: string) => s.replace(/^\/+|\/+$/g, '');
const withSlashes = (s: string) => `/${trimSlashes(s)}/`.replace(/\/+/g, '/');

export const onRequest = defineRouteMiddleware((context) => {
	const route = context.locals.starlightRoute;
	const data = route.entry.data as Record<string, any>;
	const path = withSlashes(route.id);

	// 1 · Which section (tab) is this page in?
	// Frontmatter wins, then the current starlight-sidebar-topics topic, then path prefixes.
	const topics = (context.locals as { starlightSidebarTopics?: App.Locals['starlightSidebarTopics'] })
		.starlightSidebarTopics;
	const currentTopicLink = topics?.topics.find((t) => t.isCurrent)?.link;
	const pick = () =>
		config.sections.find((s) => data.section && s.id === data.section) ??
		config.sections.find((s) => s.topic && currentTopicLink && withSlashes(s.topic) === withSlashes(currentTopicLink)) ??
		config.sections.find((s) =>
			[s.link, ...s.match].some((p) => trimSlashes(p) && path.startsWith(withSlashes(p))),
		);
	const found = route.id === '' || route.id === 'index' || route.id === '404' ? undefined : pick();
	const section: AwflowSection | undefined = found
		? { id: found.id, label: found.label, link: found.link, color: found.color, tint: found.tint }
		: undefined;
	const tabs: AwflowTab[] = config.sections.map((s) => ({
		id: s.id,
		label: s.label,
		link: s.link,
		color: s.color,
		tint: s.tint,
		isCurrent: s.id === section?.id,
	}));

	// 2 · Node metadata: frontmatter merged with the generated nodes.json (#1313) when present.
	const kind: string | undefined = data.kind;
	const node =
		kind === 'node' && data.node?.id
			? normaliseNode(data.node, data.worksIn, findNodeEntry(nodesData, data.node.id))
			: undefined;

	// 3 · Pagination: none on reference pages, otherwise scoped to the current sidebar group.
	const noPagination =
		kind === 'node' || config.noPagination.some((p) => trimSlashes(p) && path.startsWith(withSlashes(p)));
	if (noPagination) {
		route.pagination.prev = undefined;
		route.pagination.next = undefined;
	} else if (config.pagination === 'group' && route.hasSidebar) {
		scopePagination(route);
	}

	// 4 · Social image generated by src/pages/og/[...slug].ts.
	if (config.ogImages && context.site) {
		const image = new URL(`og/${route.id === '' ? 'index' : trimSlashes(route.id)}.png`, context.site).href;
		route.head.push(
			{ tag: 'meta', attrs: { property: 'og:image', content: image } },
			{ tag: 'meta', attrs: { property: 'og:image:width', content: '1200' } },
			{ tag: 'meta', attrs: { property: 'og:image:height', content: '630' } },
			{ tag: 'meta', attrs: { name: 'twitter:image', content: image } },
		);
	}

	const isSplash = data.template === 'splash';
	const showBanner =
		!isSplash &&
		(config.banner === 'auto' ? Boolean(section) || kind === 'node' : Boolean(data.section || data.kind));

	const segments = trimSlashes(route.id).split('/').slice(0, -1);
	// "use the app / usage / …" → "use the app / …": the section label already names the root folder.
	if (section && segments[0] === trimSlashes(section.link).split('/')[0]) segments.shift();
	const awflow: AwflowRouteData = {
		section,
		tabs,
		kind,
		node,
		showBanner,
		eyebrow: [section?.label.toLowerCase(), ...segments.map((s) => s.replace(/-/g, ' '))]
			.filter(Boolean)
			.join(' / '),
		markdownUrl: route.id && route.id !== 'index' ? `/${trimSlashes(route.id)}.md` : undefined,
	};
	route.awflow = awflow;
});
